# SPDX-FileCopyrightText: 2019-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: primitives.atomix.io/v2beta1
kind: Election
metadata:
  name: example-election
  labels:
    app: example
spec:
  store:
    name: example-store
---
apiVersion: primitives.atomix.io/v2beta1
kind: Map
metadata:
  name: example-map
  labels:
    app: example
spec:
  store:
    name: example-store
    config:
      gossip:
        clock:
          epoch:
            election:
              name: example-election