// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomix/election/election.proto

package election

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import headers "github.com/atomix/atomix-k8s-controller/proto/atomix/headers"
import duration "github.com/golang/protobuf/ptypes/duration"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventResponse_Type int32

const (
	EventResponse_CHANGED EventResponse_Type = 0
)

var EventResponse_Type_name = map[int32]string{
	0: "CHANGED",
}
var EventResponse_Type_value = map[string]int32{
	"CHANGED": 0,
}

func (x EventResponse_Type) String() string {
	return proto.EnumName(EventResponse_Type_name, int32(x))
}
func (EventResponse_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{19, 0}
}

type CreateRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Timeout              *duration.Duration     `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{0}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CreateRequest) GetTimeout() *duration.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

type CreateResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{1}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type KeepAliveRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *KeepAliveRequest) Reset()         { *m = KeepAliveRequest{} }
func (m *KeepAliveRequest) String() string { return proto.CompactTextString(m) }
func (*KeepAliveRequest) ProtoMessage()    {}
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{2}
}
func (m *KeepAliveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveRequest.Unmarshal(m, b)
}
func (m *KeepAliveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveRequest.Marshal(b, m, deterministic)
}
func (dst *KeepAliveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveRequest.Merge(dst, src)
}
func (m *KeepAliveRequest) XXX_Size() int {
	return xxx_messageInfo_KeepAliveRequest.Size(m)
}
func (m *KeepAliveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveRequest proto.InternalMessageInfo

func (m *KeepAliveRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type KeepAliveResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *KeepAliveResponse) Reset()         { *m = KeepAliveResponse{} }
func (m *KeepAliveResponse) String() string { return proto.CompactTextString(m) }
func (*KeepAliveResponse) ProtoMessage()    {}
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{3}
}
func (m *KeepAliveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeepAliveResponse.Unmarshal(m, b)
}
func (m *KeepAliveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeepAliveResponse.Marshal(b, m, deterministic)
}
func (dst *KeepAliveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeepAliveResponse.Merge(dst, src)
}
func (m *KeepAliveResponse) XXX_Size() int {
	return xxx_messageInfo_KeepAliveResponse.Size(m)
}
func (m *KeepAliveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeepAliveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeepAliveResponse proto.InternalMessageInfo

func (m *KeepAliveResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CloseRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Delete               bool                   `protobuf:"varint,2,opt,name=delete,proto3" json:"delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{4}
}
func (m *CloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequest.Unmarshal(m, b)
}
func (m *CloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequest.Marshal(b, m, deterministic)
}
func (dst *CloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequest.Merge(dst, src)
}
func (m *CloseRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRequest.Size(m)
}
func (m *CloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequest proto.InternalMessageInfo

func (m *CloseRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CloseRequest) GetDelete() bool {
	if m != nil {
		return m.Delete
	}
	return false
}

type CloseResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CloseResponse) Reset()         { *m = CloseResponse{} }
func (m *CloseResponse) String() string { return proto.CompactTextString(m) }
func (*CloseResponse) ProtoMessage()    {}
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{5}
}
func (m *CloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseResponse.Unmarshal(m, b)
}
func (m *CloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseResponse.Marshal(b, m, deterministic)
}
func (dst *CloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseResponse.Merge(dst, src)
}
func (m *CloseResponse) XXX_Size() int {
	return xxx_messageInfo_CloseResponse.Size(m)
}
func (m *CloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseResponse proto.InternalMessageInfo

func (m *CloseResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type EnterRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CandidateId          string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EnterRequest) Reset()         { *m = EnterRequest{} }
func (m *EnterRequest) String() string { return proto.CompactTextString(m) }
func (*EnterRequest) ProtoMessage()    {}
func (*EnterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{6}
}
func (m *EnterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterRequest.Unmarshal(m, b)
}
func (m *EnterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterRequest.Marshal(b, m, deterministic)
}
func (dst *EnterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterRequest.Merge(dst, src)
}
func (m *EnterRequest) XXX_Size() int {
	return xxx_messageInfo_EnterRequest.Size(m)
}
func (m *EnterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnterRequest proto.InternalMessageInfo

func (m *EnterRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EnterRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

type EnterResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term                 uint64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Timestamp            uint64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Leader               string                  `protobuf:"bytes,4,opt,name=leader,proto3" json:"leader,omitempty"`
	Candidates           []string                `protobuf:"bytes,5,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EnterResponse) Reset()         { *m = EnterResponse{} }
func (m *EnterResponse) String() string { return proto.CompactTextString(m) }
func (*EnterResponse) ProtoMessage()    {}
func (*EnterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{7}
}
func (m *EnterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterResponse.Unmarshal(m, b)
}
func (m *EnterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterResponse.Marshal(b, m, deterministic)
}
func (dst *EnterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterResponse.Merge(dst, src)
}
func (m *EnterResponse) XXX_Size() int {
	return xxx_messageInfo_EnterResponse.Size(m)
}
func (m *EnterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnterResponse proto.InternalMessageInfo

func (m *EnterResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EnterResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *EnterResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EnterResponse) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *EnterResponse) GetCandidates() []string {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type WithdrawRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CandidateId          string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{8}
}
func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (dst *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(dst, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *WithdrawRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

type WithdrawResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Succeeded            bool                    `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *WithdrawResponse) Reset()         { *m = WithdrawResponse{} }
func (m *WithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawResponse) ProtoMessage()    {}
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{9}
}
func (m *WithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResponse.Unmarshal(m, b)
}
func (m *WithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResponse.Marshal(b, m, deterministic)
}
func (dst *WithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResponse.Merge(dst, src)
}
func (m *WithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawResponse.Size(m)
}
func (m *WithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResponse proto.InternalMessageInfo

func (m *WithdrawResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *WithdrawResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

type AnointRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CandidateId          string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *AnointRequest) Reset()         { *m = AnointRequest{} }
func (m *AnointRequest) String() string { return proto.CompactTextString(m) }
func (*AnointRequest) ProtoMessage()    {}
func (*AnointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{10}
}
func (m *AnointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnointRequest.Unmarshal(m, b)
}
func (m *AnointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnointRequest.Marshal(b, m, deterministic)
}
func (dst *AnointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnointRequest.Merge(dst, src)
}
func (m *AnointRequest) XXX_Size() int {
	return xxx_messageInfo_AnointRequest.Size(m)
}
func (m *AnointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnointRequest proto.InternalMessageInfo

func (m *AnointRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AnointRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

type AnointResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Succeeded            bool                    `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *AnointResponse) Reset()         { *m = AnointResponse{} }
func (m *AnointResponse) String() string { return proto.CompactTextString(m) }
func (*AnointResponse) ProtoMessage()    {}
func (*AnointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{11}
}
func (m *AnointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnointResponse.Unmarshal(m, b)
}
func (m *AnointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnointResponse.Marshal(b, m, deterministic)
}
func (dst *AnointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnointResponse.Merge(dst, src)
}
func (m *AnointResponse) XXX_Size() int {
	return xxx_messageInfo_AnointResponse.Size(m)
}
func (m *AnointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnointResponse proto.InternalMessageInfo

func (m *AnointResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AnointResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

type PromoteRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CandidateId          string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PromoteRequest) Reset()         { *m = PromoteRequest{} }
func (m *PromoteRequest) String() string { return proto.CompactTextString(m) }
func (*PromoteRequest) ProtoMessage()    {}
func (*PromoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{12}
}
func (m *PromoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromoteRequest.Unmarshal(m, b)
}
func (m *PromoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromoteRequest.Marshal(b, m, deterministic)
}
func (dst *PromoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromoteRequest.Merge(dst, src)
}
func (m *PromoteRequest) XXX_Size() int {
	return xxx_messageInfo_PromoteRequest.Size(m)
}
func (m *PromoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PromoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PromoteRequest proto.InternalMessageInfo

func (m *PromoteRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PromoteRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

type PromoteResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Succeeded            bool                    `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PromoteResponse) Reset()         { *m = PromoteResponse{} }
func (m *PromoteResponse) String() string { return proto.CompactTextString(m) }
func (*PromoteResponse) ProtoMessage()    {}
func (*PromoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{13}
}
func (m *PromoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PromoteResponse.Unmarshal(m, b)
}
func (m *PromoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PromoteResponse.Marshal(b, m, deterministic)
}
func (dst *PromoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PromoteResponse.Merge(dst, src)
}
func (m *PromoteResponse) XXX_Size() int {
	return xxx_messageInfo_PromoteResponse.Size(m)
}
func (m *PromoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PromoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PromoteResponse proto.InternalMessageInfo

func (m *PromoteResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PromoteResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

type EvictRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CandidateId          string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EvictRequest) Reset()         { *m = EvictRequest{} }
func (m *EvictRequest) String() string { return proto.CompactTextString(m) }
func (*EvictRequest) ProtoMessage()    {}
func (*EvictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{14}
}
func (m *EvictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvictRequest.Unmarshal(m, b)
}
func (m *EvictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvictRequest.Marshal(b, m, deterministic)
}
func (dst *EvictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvictRequest.Merge(dst, src)
}
func (m *EvictRequest) XXX_Size() int {
	return xxx_messageInfo_EvictRequest.Size(m)
}
func (m *EvictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EvictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EvictRequest proto.InternalMessageInfo

func (m *EvictRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EvictRequest) GetCandidateId() string {
	if m != nil {
		return m.CandidateId
	}
	return ""
}

type EvictResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Succeeded            bool                    `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EvictResponse) Reset()         { *m = EvictResponse{} }
func (m *EvictResponse) String() string { return proto.CompactTextString(m) }
func (*EvictResponse) ProtoMessage()    {}
func (*EvictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{15}
}
func (m *EvictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EvictResponse.Unmarshal(m, b)
}
func (m *EvictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EvictResponse.Marshal(b, m, deterministic)
}
func (dst *EvictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EvictResponse.Merge(dst, src)
}
func (m *EvictResponse) XXX_Size() int {
	return xxx_messageInfo_EvictResponse.Size(m)
}
func (m *EvictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EvictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EvictResponse proto.InternalMessageInfo

func (m *EvictResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EvictResponse) GetSucceeded() bool {
	if m != nil {
		return m.Succeeded
	}
	return false
}

type GetLeadershipRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetLeadershipRequest) Reset()         { *m = GetLeadershipRequest{} }
func (m *GetLeadershipRequest) String() string { return proto.CompactTextString(m) }
func (*GetLeadershipRequest) ProtoMessage()    {}
func (*GetLeadershipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{16}
}
func (m *GetLeadershipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeadershipRequest.Unmarshal(m, b)
}
func (m *GetLeadershipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeadershipRequest.Marshal(b, m, deterministic)
}
func (dst *GetLeadershipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeadershipRequest.Merge(dst, src)
}
func (m *GetLeadershipRequest) XXX_Size() int {
	return xxx_messageInfo_GetLeadershipRequest.Size(m)
}
func (m *GetLeadershipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeadershipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeadershipRequest proto.InternalMessageInfo

func (m *GetLeadershipRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetLeadershipResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Term                 uint64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Timestamp            uint64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Leader               string                  `protobuf:"bytes,4,opt,name=leader,proto3" json:"leader,omitempty"`
	Candidates           []string                `protobuf:"bytes,5,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetLeadershipResponse) Reset()         { *m = GetLeadershipResponse{} }
func (m *GetLeadershipResponse) String() string { return proto.CompactTextString(m) }
func (*GetLeadershipResponse) ProtoMessage()    {}
func (*GetLeadershipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{17}
}
func (m *GetLeadershipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLeadershipResponse.Unmarshal(m, b)
}
func (m *GetLeadershipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLeadershipResponse.Marshal(b, m, deterministic)
}
func (dst *GetLeadershipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLeadershipResponse.Merge(dst, src)
}
func (m *GetLeadershipResponse) XXX_Size() int {
	return xxx_messageInfo_GetLeadershipResponse.Size(m)
}
func (m *GetLeadershipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLeadershipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLeadershipResponse proto.InternalMessageInfo

func (m *GetLeadershipResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetLeadershipResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *GetLeadershipResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetLeadershipResponse) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *GetLeadershipResponse) GetCandidates() []string {
	if m != nil {
		return m.Candidates
	}
	return nil
}

type EventRequest struct {
	Header               *headers.RequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{18}
}
func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (dst *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(dst, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetHeader() *headers.RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type EventResponse struct {
	Header               *headers.ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type                 EventResponse_Type      `protobuf:"varint,2,opt,name=type,proto3,enum=atomix.election.EventResponse_Type" json:"type,omitempty"`
	Term                 uint64                  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Timestamp            uint64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Leader               string                  `protobuf:"bytes,5,opt,name=leader,proto3" json:"leader,omitempty"`
	Candidates           []string                `protobuf:"bytes,6,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_election_f11649eb7e61712f, []int{19}
}
func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (dst *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(dst, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetHeader() *headers.ResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *EventResponse) GetType() EventResponse_Type {
	if m != nil {
		return m.Type
	}
	return EventResponse_CHANGED
}

func (m *EventResponse) GetTerm() uint64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *EventResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *EventResponse) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *EventResponse) GetCandidates() []string {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "atomix.election.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "atomix.election.CreateResponse")
	proto.RegisterType((*KeepAliveRequest)(nil), "atomix.election.KeepAliveRequest")
	proto.RegisterType((*KeepAliveResponse)(nil), "atomix.election.KeepAliveResponse")
	proto.RegisterType((*CloseRequest)(nil), "atomix.election.CloseRequest")
	proto.RegisterType((*CloseResponse)(nil), "atomix.election.CloseResponse")
	proto.RegisterType((*EnterRequest)(nil), "atomix.election.EnterRequest")
	proto.RegisterType((*EnterResponse)(nil), "atomix.election.EnterResponse")
	proto.RegisterType((*WithdrawRequest)(nil), "atomix.election.WithdrawRequest")
	proto.RegisterType((*WithdrawResponse)(nil), "atomix.election.WithdrawResponse")
	proto.RegisterType((*AnointRequest)(nil), "atomix.election.AnointRequest")
	proto.RegisterType((*AnointResponse)(nil), "atomix.election.AnointResponse")
	proto.RegisterType((*PromoteRequest)(nil), "atomix.election.PromoteRequest")
	proto.RegisterType((*PromoteResponse)(nil), "atomix.election.PromoteResponse")
	proto.RegisterType((*EvictRequest)(nil), "atomix.election.EvictRequest")
	proto.RegisterType((*EvictResponse)(nil), "atomix.election.EvictResponse")
	proto.RegisterType((*GetLeadershipRequest)(nil), "atomix.election.GetLeadershipRequest")
	proto.RegisterType((*GetLeadershipResponse)(nil), "atomix.election.GetLeadershipResponse")
	proto.RegisterType((*EventRequest)(nil), "atomix.election.EventRequest")
	proto.RegisterType((*EventResponse)(nil), "atomix.election.EventResponse")
	proto.RegisterEnum("atomix.election.EventResponse_Type", EventResponse_Type_name, EventResponse_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LeaderElectionServiceClient is the client API for LeaderElectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeaderElectionServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	Enter(ctx context.Context, in *EnterRequest, opts ...grpc.CallOption) (*EnterResponse, error)
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
	Anoint(ctx context.Context, in *AnointRequest, opts ...grpc.CallOption) (*AnointResponse, error)
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
	Evict(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EvictResponse, error)
	GetLeadership(ctx context.Context, in *GetLeadershipRequest, opts ...grpc.CallOption) (*GetLeadershipResponse, error)
	Events(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (LeaderElectionService_EventsClient, error)
}

type leaderElectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewLeaderElectionServiceClient(cc *grpc.ClientConn) LeaderElectionServiceClient {
	return &leaderElectionServiceClient{cc}
}

func (c *leaderElectionServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) KeepAlive(ctx context.Context, in *KeepAliveRequest, opts ...grpc.CallOption) (*KeepAliveResponse, error) {
	out := new(KeepAliveResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/KeepAlive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/Close", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) Enter(ctx context.Context, in *EnterRequest, opts ...grpc.CallOption) (*EnterResponse, error) {
	out := new(EnterResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/Enter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) Anoint(ctx context.Context, in *AnointRequest, opts ...grpc.CallOption) (*AnointResponse, error) {
	out := new(AnointResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/Anoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/Promote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) Evict(ctx context.Context, in *EvictRequest, opts ...grpc.CallOption) (*EvictResponse, error) {
	out := new(EvictResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/Evict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) GetLeadership(ctx context.Context, in *GetLeadershipRequest, opts ...grpc.CallOption) (*GetLeadershipResponse, error) {
	out := new(GetLeadershipResponse)
	err := c.cc.Invoke(ctx, "/atomix.election.LeaderElectionService/GetLeadership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderElectionServiceClient) Events(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (LeaderElectionService_EventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LeaderElectionService_serviceDesc.Streams[0], "/atomix.election.LeaderElectionService/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &leaderElectionServiceEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LeaderElectionService_EventsClient interface {
	Recv() (*EventResponse, error)
	grpc.ClientStream
}

type leaderElectionServiceEventsClient struct {
	grpc.ClientStream
}

func (x *leaderElectionServiceEventsClient) Recv() (*EventResponse, error) {
	m := new(EventResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LeaderElectionServiceServer is the server API for LeaderElectionService service.
type LeaderElectionServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	KeepAlive(context.Context, *KeepAliveRequest) (*KeepAliveResponse, error)
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	Enter(context.Context, *EnterRequest) (*EnterResponse, error)
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
	Anoint(context.Context, *AnointRequest) (*AnointResponse, error)
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	Evict(context.Context, *EvictRequest) (*EvictResponse, error)
	GetLeadership(context.Context, *GetLeadershipRequest) (*GetLeadershipResponse, error)
	Events(*EventRequest, LeaderElectionService_EventsServer) error
}

func RegisterLeaderElectionServiceServer(s *grpc.Server, srv LeaderElectionServiceServer) {
	s.RegisterService(&_LeaderElectionService_serviceDesc, srv)
}

func _LeaderElectionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepAliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/KeepAlive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).KeepAlive(ctx, req.(*KeepAliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/Close",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_Enter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).Enter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/Enter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).Enter(ctx, req.(*EnterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_Anoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).Anoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/Anoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).Anoint(ctx, req.(*AnointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/Promote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_Evict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).Evict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/Evict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).Evict(ctx, req.(*EvictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_GetLeadership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeadershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderElectionServiceServer).GetLeadership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atomix.election.LeaderElectionService/GetLeadership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderElectionServiceServer).GetLeadership(ctx, req.(*GetLeadershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderElectionService_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeaderElectionServiceServer).Events(m, &leaderElectionServiceEventsServer{stream})
}

type LeaderElectionService_EventsServer interface {
	Send(*EventResponse) error
	grpc.ServerStream
}

type leaderElectionServiceEventsServer struct {
	grpc.ServerStream
}

func (x *leaderElectionServiceEventsServer) Send(m *EventResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LeaderElectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "atomix.election.LeaderElectionService",
	HandlerType: (*LeaderElectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LeaderElectionService_Create_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _LeaderElectionService_KeepAlive_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _LeaderElectionService_Close_Handler,
		},
		{
			MethodName: "Enter",
			Handler:    _LeaderElectionService_Enter_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _LeaderElectionService_Withdraw_Handler,
		},
		{
			MethodName: "Anoint",
			Handler:    _LeaderElectionService_Anoint_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _LeaderElectionService_Promote_Handler,
		},
		{
			MethodName: "Evict",
			Handler:    _LeaderElectionService_Evict_Handler,
		},
		{
			MethodName: "GetLeadership",
			Handler:    _LeaderElectionService_GetLeadership_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _LeaderElectionService_Events_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "atomix/election/election.proto",
}

func init() {
	proto.RegisterFile("atomix/election/election.proto", fileDescriptor_election_f11649eb7e61712f)
}

var fileDescriptor_election_f11649eb7e61712f = []byte{
	// 707 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x6e, 0x59, 0x97, 0xad, 0xb7, 0xb5, 0x1b, 0x86, 0xa1, 0x12, 0x6d, 0xa5, 0x33, 0x02, 0xed,
	0x29, 0x43, 0x9b, 0x80, 0xe7, 0x69, 0xab, 0xd6, 0xa9, 0x30, 0x41, 0x98, 0xc4, 0x13, 0x82, 0xac,
	0xb9, 0xad, 0x86, 0xb6, 0x0e, 0x89, 0x3b, 0x98, 0xf8, 0x55, 0x3c, 0x21, 0x7e, 0x1d, 0x28, 0xb6,
	0x93, 0x26, 0x4d, 0x3a, 0x90, 0xa2, 0x22, 0xf1, 0xd4, 0xc6, 0xfe, 0x7c, 0xdf, 0x77, 0x9f, 0x93,
	0xbb, 0x83, 0xa6, 0x23, 0xf8, 0x90, 0x7d, 0xdd, 0xc5, 0x01, 0xf6, 0x04, 0xe3, 0xa3, 0xf8, 0x8f,
	0xe5, 0xf9, 0x5c, 0x70, 0xb2, 0xa6, 0xf6, 0xad, 0x68, 0xd9, 0x6c, 0x5e, 0x72, 0x7e, 0x39, 0xc0,
	0x5d, 0xb9, 0x7d, 0x3e, 0xbe, 0xd8, 0x75, 0xc7, 0xbe, 0x33, 0x39, 0x60, 0x6e, 0xea, 0x80, 0x7d,
	0x74, 0x5c, 0xf4, 0x83, 0xe8, 0x57, 0xed, 0xd2, 0x6f, 0x50, 0x3b, 0xf4, 0xd1, 0x11, 0x68, 0xe3,
	0xe7, 0x31, 0x06, 0x82, 0x3c, 0x05, 0x43, 0x21, 0x1a, 0xe5, 0x56, 0x79, 0x67, 0x65, 0x6f, 0xcb,
	0xd2, 0x84, 0xd1, 0x39, 0x0d, 0xec, 0xc8, 0x47, 0x5b, 0x83, 0xc9, 0x3e, 0x2c, 0x09, 0x36, 0x44,
	0x3e, 0x16, 0x8d, 0x5b, 0xf2, 0xdc, 0x7d, 0x4b, 0xe9, 0xb2, 0x22, 0x5d, 0xd6, 0x91, 0xd6, 0x65,
	0x47, 0x48, 0xda, 0x81, 0x7a, 0x44, 0x1e, 0x78, 0x7c, 0x14, 0x20, 0x79, 0x36, 0xc5, 0xde, 0xcc,
	0xb2, 0x2b, 0x64, 0x9a, 0x9e, 0x9e, 0xc0, 0x7a, 0x17, 0xd1, 0x3b, 0x18, 0xb0, 0xab, 0x82, 0x99,
	0xd0, 0x2e, 0xdc, 0x4e, 0x84, 0x2a, 0xa8, 0xeb, 0x1d, 0xac, 0x1e, 0x0e, 0x78, 0x50, 0xd4, 0xdd,
	0x7b, 0x60, 0xb8, 0x38, 0x40, 0x81, 0xd2, 0xdc, 0x65, 0x5b, 0x3f, 0xd1, 0x63, 0xa8, 0xe9, 0xf0,
	0x05, 0x75, 0xf6, 0x61, 0xb5, 0x3d, 0x12, 0xe8, 0x17, 0xd4, 0xb9, 0x0d, 0xab, 0x3d, 0x67, 0xe4,
	0x32, 0xd7, 0x11, 0xf8, 0x9e, 0xb9, 0x52, 0x6d, 0xd5, 0x5e, 0x89, 0xd7, 0x4e, 0x5c, 0xfa, 0xbd,
	0x0c, 0x35, 0x4d, 0x55, 0x4c, 0x33, 0x21, 0x50, 0x11, 0xe8, 0x0f, 0x25, 0x49, 0xc5, 0x96, 0xff,
	0xc9, 0x26, 0x54, 0xc3, 0x97, 0x2b, 0x10, 0xce, 0xd0, 0x6b, 0x2c, 0xc8, 0x8d, 0xc9, 0x42, 0x68,
	0xe3, 0x40, 0x31, 0x55, 0xa4, 0x30, 0xfd, 0x44, 0x9a, 0x00, 0xb1, 0xc4, 0xa0, 0xb1, 0xd8, 0x5a,
	0xd8, 0xa9, 0xda, 0x89, 0x15, 0xfa, 0x09, 0xd6, 0xde, 0x32, 0xd1, 0x77, 0x7d, 0xe7, 0xcb, 0xfc,
	0x0d, 0xea, 0xc3, 0xfa, 0x84, 0xac, 0xa0, 0x45, 0x9b, 0x50, 0x0d, 0xc6, 0xbd, 0x1e, 0xa2, 0x8b,
	0xae, 0x7e, 0x75, 0x26, 0x0b, 0x94, 0x41, 0xed, 0x60, 0xc4, 0xd9, 0x48, 0xcc, 0x3f, 0xa9, 0x0b,
	0xa8, 0x47, 0x54, 0x73, 0x4d, 0xe9, 0x23, 0xd4, 0x5f, 0xf9, 0x7c, 0xc8, 0x0b, 0xd7, 0xb3, 0xbf,
	0xc8, 0xe9, 0x12, 0xd6, 0x62, 0xae, 0xb9, 0x26, 0x15, 0x7e, 0x9c, 0x57, 0xac, 0xf7, 0x0f, 0xae,
	0x09, 0xa1, 0xa6, 0x99, 0xe6, 0x9a, 0xd0, 0x4b, 0xb8, 0x7b, 0x8c, 0xe2, 0x85, 0x0a, 0xd1, 0x67,
	0x5e, 0xc1, 0x8a, 0xfd, 0xb3, 0x0c, 0x1b, 0x53, 0xf1, 0xfe, 0x9b, 0xd2, 0xd2, 0x0e, 0xef, 0x16,
	0x8b, 0x7e, 0x82, 0xf4, 0x57, 0x58, 0x55, 0x55, 0x9c, 0x82, 0xa9, 0x3f, 0x87, 0x8a, 0xb8, 0xf6,
	0x54, 0xa3, 0xa9, 0xef, 0x3d, 0xb4, 0xa6, 0xc6, 0x0d, 0x2b, 0xc5, 0x62, 0x9d, 0x5d, 0x7b, 0x68,
	0xcb, 0x03, 0xb1, 0x67, 0x0b, 0xb3, 0x3c, 0xab, 0xcc, 0xf6, 0x6c, 0xf1, 0x06, 0xcf, 0x8c, 0x8c,
	0x67, 0x77, 0xa0, 0x12, 0xf2, 0x92, 0x15, 0x58, 0x3a, 0xec, 0x1c, 0x9c, 0x1e, 0xb7, 0x8f, 0xd6,
	0x4b, 0x7b, 0x3f, 0x0c, 0xd8, 0x50, 0x6f, 0x40, 0x5b, 0x4b, 0x7d, 0x83, 0xfe, 0x15, 0xeb, 0x21,
	0xe9, 0x82, 0xa1, 0xa6, 0x0c, 0xd2, 0xcc, 0x64, 0x93, 0x9a, 0x7d, 0xcc, 0x07, 0x33, 0xf7, 0x55,
	0xba, 0xb4, 0x44, 0xce, 0xa0, 0x1a, 0x4f, 0x07, 0x64, 0x3b, 0x83, 0x9f, 0x1e, 0x42, 0x4c, 0x7a,
	0x13, 0x24, 0x8e, 0xda, 0x81, 0x45, 0xd9, 0xc7, 0xc9, 0x56, 0x56, 0x41, 0x62, 0x7c, 0x30, 0x9b,
	0xb3, 0xb6, 0x93, 0x91, 0x64, 0x77, 0xcd, 0x89, 0x94, 0x6c, 0xf0, 0x39, 0x91, 0x52, 0x4d, 0x99,
	0x96, 0xc8, 0x6b, 0x58, 0x8e, 0xfa, 0x10, 0x69, 0x65, 0xd0, 0x53, 0xfd, 0xd0, 0xdc, 0xbe, 0x01,
	0x11, 0x87, 0xec, 0x82, 0xa1, 0xba, 0x40, 0xce, 0x4d, 0xa4, 0x3a, 0x51, 0xce, 0x4d, 0xa4, 0xdb,
	0x07, 0x2d, 0x91, 0x53, 0x58, 0xd2, 0xe5, 0x97, 0x64, 0xd1, 0xe9, 0x26, 0x60, 0xb6, 0x66, 0x03,
	0x52, 0xce, 0x85, 0xb5, 0x2f, 0xcf, 0xb9, 0x44, 0xf5, 0xcd, 0x73, 0x2e, 0x59, 0x32, 0x69, 0x89,
	0x7c, 0x80, 0x5a, 0xaa, 0x1c, 0x91, 0x47, 0x99, 0x23, 0x79, 0xe5, 0xcf, 0x7c, 0xfc, 0x27, 0x58,
	0xd2, 0x48, 0xf9, 0x1d, 0x06, 0xb9, 0x62, 0x27, 0xe5, 0x24, 0x57, 0x2c, 0x26, 0x6d, 0x7c, 0x52,
	0x3e, 0x37, 0xe4, 0x84, 0xbe, 0xff, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xb1, 0x3f, 0xe9, 0x7a,
	0x0c, 0x00, 0x00,
}
