sudo: false

language: go

go:
  - '1.13.x'

services:
  - 'docker'

notifications:
  email: false

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  directories:
    - $HOME/gopath/pkg/mod         # Cache the Go modules

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - pushd .. && git clone https://github.com/onosproject/build-tools.git && popd

jobs:
  include:
    - stage: docs build
      if: type != pull_request
      script:
        - sh ../build-tools/build/travis/trigger-travis atomix docs master "`git rev-parse --short HEAD`" $TRAVIS_API_TOKEN
    - stage: test
      script:
          - make test

deploy:
  - provider: script
    script: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./build/bin/push-images; fi'
    on:
      branch: master
  - provider: script
    script: VERSION=$TRAVIS_TAG ./build/bin/push-images
    on:
      tags: true
      all_branches: true
