# SPDX-FileCopyrightText: 2019-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: atomix.io/v2beta1
kind: Store
metadata:
  name: example-store
spec:
  protocol:
    apiVersion: storage.atomix.io/v2beta1
    kind: NOPaxosProtocol
    spec:
      clusters: 1
      partitions: 1
      replicas: 3
