apiVersion: atomix.io/v2beta1
kind: Store
metadata:
  name: store
spec:
  protocol:
    apiVersion: storage.atomix.io/v2beta1
    kind: RaftProtocol
    spec:
      clusters: 1
      partitions: 1
      replicas: 3
