apiVersion: atomix.io/v2beta1
kind: Store
metadata:
  name: example-store
spec:
  protocol:
    apiVersion: storage.atomix.io/v2beta2
    kind: MultiRaftProtocol
    spec:
      replicas: 3
      groups: 10
      raft:
        quorumSize: 3
        readReplicas: 0
        sessionTimeout: 30s
        snapshotEntryThreshold: 10000
