apiVersion: atomix.io/v2beta1
kind: Store
metadata:
  name: example-store
spec:
  protocol:
    apiVersion: storage.atomix.io/v2beta2
    kind: MultiRaftProtocol
    spec:
      cluster:
        replicas: 3
        groups: 3
        template:
          spec:
            raftConfig:
              snapshotStrategy:
                type: Threshold
                entryThreshold: 10
