apiVersion: v1
kind: ServiceAccount
metadata:
  name: raft-primitives
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: raft-primitives
rules:
- apiGroups:
  - primitives.k8s.atomix.io
  resources:
  - '*'
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: raft-primitives
subjects:
- kind: ServiceAccount
  name: raft-primitives
roleRef:
  kind: Role
  name: raft-primitives
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
  annotations:
    broker.atomix.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccountName: raft-primitives
      containers:
      - name: sleep
        image: alpine:latest
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 30; done;"]