// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleProtocol) DeepCopyInto(out *ExampleProtocol) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleProtocol.
func (in *ExampleProtocol) DeepCopy() *ExampleProtocol {
	if in == nil {
		return nil
	}
	out := new(ExampleProtocol)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExampleProtocol) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleProtocolBackend) DeepCopyInto(out *ExampleProtocolBackend) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleProtocolBackend.
func (in *ExampleProtocolBackend) DeepCopy() *ExampleProtocolBackend {
	if in == nil {
		return nil
	}
	out := new(ExampleProtocolBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleProtocolList) DeepCopyInto(out *ExampleProtocolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExampleProtocol, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleProtocolList.
func (in *ExampleProtocolList) DeepCopy() *ExampleProtocolList {
	if in == nil {
		return nil
	}
	out := new(ExampleProtocolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExampleProtocolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleProtocolProxy) DeepCopyInto(out *ExampleProtocolProxy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleProtocolProxy.
func (in *ExampleProtocolProxy) DeepCopy() *ExampleProtocolProxy {
	if in == nil {
		return nil
	}
	out := new(ExampleProtocolProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleProtocolSpec) DeepCopyInto(out *ExampleProtocolSpec) {
	*out = *in
	out.Proxy = in.Proxy
	out.Backend = in.Backend
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleProtocolSpec.
func (in *ExampleProtocolSpec) DeepCopy() *ExampleProtocolSpec {
	if in == nil {
		return nil
	}
	out := new(ExampleProtocolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleProtocolStatus) DeepCopyInto(out *ExampleProtocolStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleProtocolStatus.
func (in *ExampleProtocolStatus) DeepCopy() *ExampleProtocolStatus {
	if in == nil {
		return nil
	}
	out := new(ExampleProtocolStatus)
	in.DeepCopyInto(out)
	return out
}
