/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/atomix/atomix-k8s-controller/pkg/apis/k8s/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePartitionSets implements PartitionSetInterface
type FakePartitionSets struct {
	Fake *FakeK8sV1alpha1
	ns   string
}

var partitionsetsResource = schema.GroupVersionResource{Group: "k8s.atomix.io", Version: "v1alpha1", Resource: "partitionsets"}

var partitionsetsKind = schema.GroupVersionKind{Group: "k8s.atomix.io", Version: "v1alpha1", Kind: "PartitionSet"}

// Get takes name of the partitionSet, and returns the corresponding partitionSet object, and an error if there is any.
func (c *FakePartitionSets) Get(name string, options v1.GetOptions) (result *v1alpha1.PartitionSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(partitionsetsResource, c.ns, name), &v1alpha1.PartitionSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartitionSet), err
}

// List takes label and field selectors, and returns the list of PartitionSets that match those selectors.
func (c *FakePartitionSets) List(opts v1.ListOptions) (result *v1alpha1.PartitionSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(partitionsetsResource, partitionsetsKind, c.ns, opts), &v1alpha1.PartitionSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PartitionSetList{ListMeta: obj.(*v1alpha1.PartitionSetList).ListMeta}
	for _, item := range obj.(*v1alpha1.PartitionSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested partitionSets.
func (c *FakePartitionSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(partitionsetsResource, c.ns, opts))

}

// Create takes the representation of a partitionSet and creates it.  Returns the server's representation of the partitionSet, and an error, if there is any.
func (c *FakePartitionSets) Create(partitionSet *v1alpha1.PartitionSet) (result *v1alpha1.PartitionSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(partitionsetsResource, c.ns, partitionSet), &v1alpha1.PartitionSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartitionSet), err
}

// Update takes the representation of a partitionSet and updates it. Returns the server's representation of the partitionSet, and an error, if there is any.
func (c *FakePartitionSets) Update(partitionSet *v1alpha1.PartitionSet) (result *v1alpha1.PartitionSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(partitionsetsResource, c.ns, partitionSet), &v1alpha1.PartitionSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartitionSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePartitionSets) UpdateStatus(partitionSet *v1alpha1.PartitionSet) (*v1alpha1.PartitionSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(partitionsetsResource, "status", c.ns, partitionSet), &v1alpha1.PartitionSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartitionSet), err
}

// Delete takes name of the partitionSet and deletes it. Returns an error if one occurs.
func (c *FakePartitionSets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(partitionsetsResource, c.ns, name), &v1alpha1.PartitionSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePartitionSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(partitionsetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PartitionSetList{})
	return err
}

// Patch applies the patch and returns the patched partitionSet.
func (c *FakePartitionSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PartitionSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(partitionsetsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PartitionSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PartitionSet), err
}
