apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.cloud.atomix.io
spec:
  group: cloud.atomix.io
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
  scope: Namespaced
  version: v1beta1
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.cloud.atomix.io
spec:
  group: cloud.atomix.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  version: v1beta1
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: partitions.cloud.atomix.io
spec:
  group: cloud.atomix.io
  names:
    kind: Partition
    listKind: PartitionList
    plural: partitions
    singular: partition
  scope: Namespaced
  version: v1beta1
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: Protocol
metadata:
  name: protocols.cloud.atomix.io
spec:
  group: cloud.atomix.io
  names:
    kind: Protocol
    listKind: ProtocolList
    plural: protocols
    singular: protocol
  scope: Cluster
  version: v1beta1
  subresources:
    status: {}