# SPDX-FileCopyrightText: 2019-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: atomix.io/v2beta1
kind: StorageProfile
metadata:
  name: example-profile
  labels:
    app: example
spec:
  drivers:
  - raft.storage.atomix.io
  - gossip.storage.atomix.io
  selector:
    matchLabels:
      app: example
