// Code generated by protoc-gen-go. DO NOT EDIT.
// source: atomix/headers/headers.proto

package atomix_headers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Namespaced primitive name
type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_headers_9221e50e0b515c13, []int{0}
}
func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (dst *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(dst, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Name) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type RequestHeader struct {
	Name                 *Name           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SessionId            uint64          `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Index                uint64          `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	SequenceNumber       uint64          `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Streams              []*StreamHeader `protobuf:"bytes,5,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_headers_9221e50e0b515c13, []int{1}
}
func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (dst *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(dst, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RequestHeader) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *RequestHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *RequestHeader) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *RequestHeader) GetStreams() []*StreamHeader {
	if m != nil {
		return m.Streams
	}
	return nil
}

type ResponseHeader struct {
	SessionId            uint64          `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Index                uint64          `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	SequenceNumber       uint64          `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Streams              []*StreamHeader `protobuf:"bytes,4,rep,name=streams,proto3" json:"streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ResponseHeader) Reset()         { *m = ResponseHeader{} }
func (m *ResponseHeader) String() string { return proto.CompactTextString(m) }
func (*ResponseHeader) ProtoMessage()    {}
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_headers_9221e50e0b515c13, []int{2}
}
func (m *ResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseHeader.Unmarshal(m, b)
}
func (m *ResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseHeader.Marshal(b, m, deterministic)
}
func (dst *ResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseHeader.Merge(dst, src)
}
func (m *ResponseHeader) XXX_Size() int {
	return xxx_messageInfo_ResponseHeader.Size(m)
}
func (m *ResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseHeader proto.InternalMessageInfo

func (m *ResponseHeader) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *ResponseHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ResponseHeader) GetSequenceNumber() uint64 {
	if m != nil {
		return m.SequenceNumber
	}
	return 0
}

func (m *ResponseHeader) GetStreams() []*StreamHeader {
	if m != nil {
		return m.Streams
	}
	return nil
}

type StreamHeader struct {
	StreamId             uint64   `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	LastItemNumber       uint64   `protobuf:"varint,3,opt,name=last_item_number,json=lastItemNumber,proto3" json:"last_item_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamHeader) Reset()         { *m = StreamHeader{} }
func (m *StreamHeader) String() string { return proto.CompactTextString(m) }
func (*StreamHeader) ProtoMessage()    {}
func (*StreamHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_headers_9221e50e0b515c13, []int{3}
}
func (m *StreamHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamHeader.Unmarshal(m, b)
}
func (m *StreamHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamHeader.Marshal(b, m, deterministic)
}
func (dst *StreamHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamHeader.Merge(dst, src)
}
func (m *StreamHeader) XXX_Size() int {
	return xxx_messageInfo_StreamHeader.Size(m)
}
func (m *StreamHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamHeader.DiscardUnknown(m)
}

var xxx_messageInfo_StreamHeader proto.InternalMessageInfo

func (m *StreamHeader) GetStreamId() uint64 {
	if m != nil {
		return m.StreamId
	}
	return 0
}

func (m *StreamHeader) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StreamHeader) GetLastItemNumber() uint64 {
	if m != nil {
		return m.LastItemNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*Name)(nil), "atomix.headers.Name")
	proto.RegisterType((*RequestHeader)(nil), "atomix.headers.RequestHeader")
	proto.RegisterType((*ResponseHeader)(nil), "atomix.headers.ResponseHeader")
	proto.RegisterType((*StreamHeader)(nil), "atomix.headers.StreamHeader")
}

func init() {
	proto.RegisterFile("atomix/headers/headers.proto", fileDescriptor_headers_9221e50e0b515c13)
}

var fileDescriptor_headers_9221e50e0b515c13 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xe9, 0xda, 0xa9, 0x3d, 0xd3, 0x2a, 0x61, 0x17, 0x05, 0x2b, 0x8c, 0xde, 0xd8, 0xab,
	0x0a, 0x13, 0xc4, 0x47, 0x70, 0x37, 0xbb, 0x88, 0x0f, 0x50, 0xb2, 0xf5, 0x80, 0x41, 0x93, 0xd4,
	0x9e, 0x0c, 0xf6, 0x44, 0xbe, 0x8e, 0xaf, 0x24, 0x4d, 0x5a, 0xf6, 0x07, 0xc6, 0xf0, 0xea, 0xb4,
	0xdf, 0x2f, 0x7c, 0xe7, 0x17, 0x08, 0x64, 0xc2, 0x1a, 0x25, 0xb7, 0x4f, 0x1f, 0x28, 0x6a, 0x6c,
	0x69, 0x98, 0x65, 0xd3, 0x1a, 0x6b, 0x58, 0xe2, 0x69, 0xd9, 0xa7, 0xf9, 0x2b, 0x44, 0x4b, 0xa1,
	0x90, 0x31, 0x88, 0xb4, 0x50, 0x98, 0x06, 0xb3, 0xa0, 0x88, 0xb9, 0xfb, 0x66, 0x19, 0xc4, 0xdd,
	0xa4, 0x46, 0xac, 0x31, 0x1d, 0x39, 0xb0, 0x0b, 0xf2, 0xdf, 0x00, 0x6e, 0x38, 0x7e, 0x6f, 0x90,
	0xec, 0x9b, 0x2b, 0x63, 0xc5, 0x5e, 0xc7, 0x64, 0x3e, 0x2d, 0x0f, 0x57, 0x95, 0xdd, 0x9e, 0xbe,
	0xf9, 0x01, 0x80, 0x90, 0x48, 0x1a, 0x5d, 0xc9, 0xda, 0x55, 0x47, 0x3c, 0xee, 0x93, 0x45, 0xcd,
	0xa6, 0x30, 0x96, 0xba, 0xc6, 0x6d, 0x1a, 0x3a, 0xe2, 0x7f, 0xd8, 0x23, 0xdc, 0x52, 0xb7, 0x4f,
	0xaf, 0xb1, 0xd2, 0x1b, 0xb5, 0xc2, 0x36, 0x8d, 0x1c, 0x4f, 0x86, 0x78, 0xe9, 0x52, 0xf6, 0x02,
	0x97, 0x64, 0x5b, 0x14, 0x8a, 0xd2, 0xf1, 0x2c, 0x2c, 0x26, 0xf3, 0xec, 0x58, 0xe5, 0xdd, 0x61,
	0xaf, 0xcd, 0x87, 0xc3, 0xf9, 0x4f, 0x00, 0x09, 0x47, 0x6a, 0x8c, 0x26, 0xec, 0xaf, 0x74, 0x28,
	0x1a, 0x9c, 0x14, 0x1d, 0x9d, 0x11, 0x0d, 0xcf, 0x89, 0x46, 0xff, 0x11, 0xfd, 0x84, 0xeb, 0x7d,
	0xc0, 0xee, 0x21, 0xf6, 0x68, 0x27, 0x79, 0xe5, 0x83, 0x93, 0x8e, 0x05, 0xdc, 0x7d, 0x09, 0xb2,
	0x95, 0xb4, 0xa8, 0x8e, 0x24, 0xbb, 0x7c, 0x61, 0x51, 0x79, 0xc9, 0xd5, 0x85, 0x7b, 0x38, 0xcf,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x5b, 0xa4, 0x45, 0x58, 0x02, 0x00, 0x00,
}
